/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.ctrlInicioNutricionista;
import modelo.Dieta;
import modelo.cbClientes;

/**
 *
 * @author PC
 */
public class FrmInicioNutricioniosta extends javax.swing.JFrame {

    /**
     * Creates new form FrmInicioNutricioniosta
     */
    public FrmInicioNutricioniosta() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public static void initNutricionista(){
        
        cbClientes modeloCliente = new cbClientes();
        Dieta modeloDieta = new Dieta();
        FrmInicioNutricioniosta vista = new FrmInicioNutricioniosta();
        ctrlInicioNutricionista controlador = new ctrlInicioNutricionista(vista, modeloCliente, modeloDieta);
        
        vista.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlmuerzo = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDesayuno = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCena = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtRefrigerios = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        cbIdCliente = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnAgregarDieta = new javax.swing.JButton();
        btnActualizarDieta = new javax.swing.JButton();
        btnEliminarDieta = new javax.swing.JButton();
        btnLimpiarDieta = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTBdietaCRUD = new javax.swing.JTable();
        btnVerClientesDieta = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1267, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(69, 69, 69));
        jLabel2.setText("asignara la dieta aqui:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 69, 69));
        jLabel3.setText("Desayuno");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 69, 69));
        jLabel4.setText("Almuerzo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, -1, -1));

        txtAlmuerzo.setColumns(20);
        txtAlmuerzo.setRows(5);
        jScrollPane1.setViewportView(txtAlmuerzo);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 380, 100));

        txtDesayuno.setColumns(20);
        txtDesayuno.setRows(5);
        jScrollPane2.setViewportView(txtDesayuno);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 380, 100));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 69, 69));
        jLabel5.setText("Cena");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 120, 40, -1));

        txtCena.setColumns(20);
        txtCena.setRows(5);
        jScrollPane3.setViewportView(txtCena);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 150, 380, 100));

        txtRefrigerios.setColumns(20);
        txtRefrigerios.setRows(5);
        jScrollPane4.setViewportView(txtRefrigerios);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 380, 100));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(69, 69, 69));
        jLabel6.setText("Refrigerios");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, 30));

        cbIdCliente.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        cbIdCliente.setForeground(new java.awt.Color(69, 69, 69));
        cbIdCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 280, 301, 40));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 69, 69));
        jLabel7.setText("Cliente al que se le asignara la dieta");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 250, -1, 30));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(69, 69, 69));
        jLabel9.setText("Agrega una nueva dieta");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, -1, -1));

        btnAgregarDieta.setBackground(new java.awt.Color(69, 69, 69));
        btnAgregarDieta.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        btnAgregarDieta.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarDieta.setText("Agregar");
        btnAgregarDieta.setBorder(null);
        jPanel1.add(btnAgregarDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 410, 130, 40));

        btnActualizarDieta.setBackground(new java.awt.Color(69, 69, 69));
        btnActualizarDieta.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        btnActualizarDieta.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarDieta.setText("Editar");
        btnActualizarDieta.setBorder(null);
        jPanel1.add(btnActualizarDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 480, 130, 40));

        btnEliminarDieta.setBackground(new java.awt.Color(69, 69, 69));
        btnEliminarDieta.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        btnEliminarDieta.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarDieta.setText("Eliminar");
        btnEliminarDieta.setBorder(null);
        jPanel1.add(btnEliminarDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 550, 130, 40));

        btnLimpiarDieta.setBackground(new java.awt.Color(69, 69, 69));
        btnLimpiarDieta.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        btnLimpiarDieta.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarDieta.setText("Limpiar");
        btnLimpiarDieta.setBorder(null);
        btnLimpiarDieta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarDietaActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiarDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 620, 130, 40));

        jScrollPane5.setBorder(null);

        jTBdietaCRUD.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        jTBdietaCRUD.setForeground(new java.awt.Color(69, 69, 69));
        jTBdietaCRUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTBdietaCRUD);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 1020, 250));

        btnVerClientesDieta.setBackground(new java.awt.Color(210, 203, 236));
        btnVerClientesDieta.setFont(new java.awt.Font("Leelawadee UI", 1, 13)); // NOI18N
        btnVerClientesDieta.setForeground(new java.awt.Color(255, 255, 255));
        btnVerClientesDieta.setText("Clientes");
        btnVerClientesDieta.setBorder(null);
        jPanel1.add(btnVerClientesDieta, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 150, 40));

        jLabel8.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(69, 69, 69));
        jLabel8.setText("IMPORTANTE: primero revisar a que cliente se le ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, -1, -1));

        btnCerrarSesion.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnCerrarSesion.setText("Cerrar Sesion");
        jPanel1.add(btnCerrarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 690, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarDietaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarDietaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLimpiarDietaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInicioNutricioniosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInicioNutricioniosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInicioNutricioniosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInicioNutricioniosta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initNutricionista();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarDieta;
    public javax.swing.JButton btnAgregarDieta;
    public javax.swing.JLabel btnCerrarSesion;
    public javax.swing.JButton btnEliminarDieta;
    public javax.swing.JButton btnLimpiarDieta;
    public javax.swing.JButton btnVerClientesDieta;
    public javax.swing.JComboBox<String> cbIdCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jTBdietaCRUD;
    public javax.swing.JTextArea txtAlmuerzo;
    public javax.swing.JTextArea txtCena;
    public javax.swing.JTextArea txtDesayuno;
    public javax.swing.JTextArea txtRefrigerios;
    // End of variables declaration//GEN-END:variables
}
