/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ctrlCRUDnutricionista;
import modelo.Nutricionista;

/**
 *
 * @author PC
 */
public class panelNutricionista extends javax.swing.JPanel {

    /**
     * Creates new form panelNutricionista
     */
    public panelNutricionista() {
        initComponents();
        
        Nutricionista modelo = new Nutricionista();
        panelNutricionista panelCrudN = this;
        ctrlCRUDnutricionista controlador = new ctrlCRUDnutricionista(panelCrudN, modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtClaveNutri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroNutri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreNutri = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEdadNutri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreoNutri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBnutricionistaCRUD = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1267, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(46, 52, 64));
        btnAgregar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 410, 130, 50));

        btnEliminar.setBackground(new java.awt.Color(46, 52, 64));
        btnEliminar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, 130, 50));

        btnLimpiar.setBackground(new java.awt.Color(46, 52, 64));
        btnLimpiar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 620, 130, 50));

        txtClaveNutri.setBackground(new java.awt.Color(210, 203, 236));
        txtClaveNutri.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        txtClaveNutri.setForeground(new java.awt.Color(69, 69, 69));
        txtClaveNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveNutriActionPerformed(evt);
            }
        });
        add(txtClaveNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 350, 45));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(69, 69, 69));
        jLabel4.setText("Contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, -1, -1));

        txtNumeroNutri.setBackground(new java.awt.Color(210, 203, 236));
        txtNumeroNutri.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        txtNumeroNutri.setForeground(new java.awt.Color(69, 69, 69));
        add(txtNumeroNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 350, 45));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(69, 69, 69));
        jLabel3.setText("Numero");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel2.setText("Agrega un nuevo nutricionista");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        txtNombreNutri.setBackground(new java.awt.Color(210, 203, 236));
        txtNombreNutri.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        txtNombreNutri.setForeground(new java.awt.Color(69, 69, 69));
        add(txtNombreNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 350, 45));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(69, 69, 69));
        jLabel5.setText("Nombre");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtEdadNutri.setBackground(new java.awt.Color(210, 203, 236));
        txtEdadNutri.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        txtEdadNutri.setForeground(new java.awt.Color(69, 69, 69));
        txtEdadNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadNutriActionPerformed(evt);
            }
        });
        add(txtEdadNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 350, 45));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(69, 69, 69));
        jLabel6.setText("Edad");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtCorreoNutri.setBackground(new java.awt.Color(210, 203, 236));
        txtCorreoNutri.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 14)); // NOI18N
        txtCorreoNutri.setForeground(new java.awt.Color(69, 69, 69));
        txtCorreoNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoNutriActionPerformed(evt);
            }
        });
        add(txtCorreoNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 350, 45));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(69, 69, 69));
        jLabel7.setText("Correo electronico");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 120, -1, -1));

        jTBnutricionistaCRUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBnutricionistaCRUD);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 760, 260));

        btnActualizar.setBackground(new java.awt.Color(46, 52, 64));
        btnActualizar.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Editar");
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 550, 130, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveNutriActionPerformed

    private void txtEdadNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadNutriActionPerformed

    private void txtCorreoNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoNutriActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTBnutricionistaCRUD;
    public javax.swing.JTextField txtClaveNutri;
    public javax.swing.JTextField txtCorreoNutri;
    public javax.swing.JTextField txtEdadNutri;
    public javax.swing.JTextField txtNombreNutri;
    public javax.swing.JTextField txtNumeroNutri;
    // End of variables declaration//GEN-END:variables
}
