/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ctrlCRUDnutricionista;
import modelo.Nutricionista;

/**
 *
 * @author PC
 */
public class panelNutricionista extends javax.swing.JPanel {

    /**
     * Creates new form panelNutricionista
     */
    public panelNutricionista() {
        initComponents();
        
        Nutricionista modelo = new Nutricionista();
        panelNutricionista panelCrudN = this;
        ctrlCRUDnutricionista controlador = new ctrlCRUDnutricionista(panelCrudN, modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtClaveNutri = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroNutri = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtNombreNutri = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEdadNutri = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCorreoNutri = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBnutricionistaCRUD = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setBackground(new java.awt.Color(118, 99, 242));
        btnAgregar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 159, 54));

        btnEliminar.setBackground(new java.awt.Color(118, 99, 242));
        btnEliminar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnEliminar.setText("Eliminar");
        add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 620, 158, 54));

        btnLimpiar.setBackground(new java.awt.Color(118, 99, 242));
        btnLimpiar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnLimpiar.setText("Limpiar");
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 620, 160, 54));

        txtClaveNutri.setBackground(new java.awt.Color(221, 221, 221));
        txtClaveNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveNutriActionPerformed(evt);
            }
        });
        add(txtClaveNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 350, 44));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Contraseña");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        txtNumeroNutri.setBackground(new java.awt.Color(221, 221, 221));
        add(txtNumeroNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 350, 43));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Numero");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresar nuevo nutricionista");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Bienvenido a HEALTHSYNC");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jButton1.setBackground(new java.awt.Color(118, 99, 242));
        jButton1.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        jButton1.setText("Salir");
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 18, 138, -1));

        txtNombreNutri.setBackground(new java.awt.Color(221, 221, 221));
        add(txtNombreNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 350, 43));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Nombre");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        txtEdadNutri.setBackground(new java.awt.Color(221, 221, 221));
        txtEdadNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadNutriActionPerformed(evt);
            }
        });
        add(txtEdadNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 350, 44));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Edad");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtCorreoNutri.setBackground(new java.awt.Color(221, 221, 221));
        txtCorreoNutri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoNutriActionPerformed(evt);
            }
        });
        add(txtCorreoNutri, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 350, 44));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Correo electronico");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jTBnutricionistaCRUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTBnutricionistaCRUD);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 850, 180));

        btnActualizar.setBackground(new java.awt.Color(118, 99, 242));
        btnActualizar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnActualizar.setText("Editar");
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 620, 160, 54));
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveNutriActionPerformed

    private void txtEdadNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadNutriActionPerformed

    private void txtCorreoNutriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoNutriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoNutriActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnLimpiar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTBnutricionistaCRUD;
    public javax.swing.JTextField txtClaveNutri;
    public javax.swing.JTextField txtCorreoNutri;
    public javax.swing.JTextField txtEdadNutri;
    public javax.swing.JTextField txtNombreNutri;
    public javax.swing.JTextField txtNumeroNutri;
    // End of variables declaration//GEN-END:variables
}
