/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import controlador.ctrlCRUDconsejo;
import modelo.Consejos;
import modelo.cbClientes;

/**
 *
 * @author PC
 */
public class panelConsejosE extends javax.swing.JPanel {

    /**
     * Creates new form panelConsejosE
     */
    public panelConsejosE() {
        initComponents();
        
        Consejos modeloConsejo = new Consejos();
        cbClientes modeloClientes = new cbClientes();
        panelConsejosE panel = this;
        ctrlCRUDconsejo controlador = new ctrlCRUDconsejo(panel, modeloClientes, modeloConsejo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtConsejoEntrenar = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtConsejoDia = new javax.swing.JTextArea();
        cbClienteIdConsejo = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAgregarConsejo = new javax.swing.JButton();
        btnEliminarConsejo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizarConsejo = new javax.swing.JButton();
        btnVerClientes4 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTBconsejoCRUD = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ingresa unos consejos");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Bienvenido a HEALTHSYNC");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Consejo para entrenar");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Selecciona el cliente al que le agregaras los consejos");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, -1));

        txtConsejoEntrenar.setColumns(20);
        txtConsejoEntrenar.setRows(5);
        jScrollPane1.setViewportView(txtConsejoEntrenar);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 110));

        txtConsejoDia.setColumns(20);
        txtConsejoDia.setRows(5);
        jScrollPane2.setViewportView(txtConsejoDia);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 110));

        cbClienteIdConsejo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cbClienteIdConsejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 300, 50));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Consejo del dia");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("IMPORTANTE: primero revisar a que cliente se le asignara la dieta aqui:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        btnAgregarConsejo.setBackground(new java.awt.Color(118, 99, 242));
        btnAgregarConsejo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnAgregarConsejo.setText("Agregar");
        add(btnAgregarConsejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 181, 54));

        btnEliminarConsejo.setBackground(new java.awt.Color(118, 99, 242));
        btnEliminarConsejo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnEliminarConsejo.setText("Eliminar");
        add(btnEliminarConsejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 181, 54));

        btnLimpiar.setBackground(new java.awt.Color(118, 99, 242));
        btnLimpiar.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnLimpiar.setText("Limpiar");
        add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 181, 54));

        btnActualizarConsejo.setBackground(new java.awt.Color(118, 99, 242));
        btnActualizarConsejo.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnActualizarConsejo.setText("Editar");
        add(btnActualizarConsejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 181, 54));

        btnVerClientes4.setBackground(new java.awt.Color(118, 99, 242));
        btnVerClientes4.setFont(new java.awt.Font("Leelawadee UI", 1, 24)); // NOI18N
        btnVerClientes4.setText("Clientes");
        add(btnVerClientes4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 181, 54));

        jTBconsejoCRUD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTBconsejoCRUD);

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 850, 180));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarConsejo;
    public javax.swing.JButton btnAgregarConsejo;
    public javax.swing.JButton btnEliminarConsejo;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnVerClientes4;
    public javax.swing.JComboBox<String> cbClienteIdConsejo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jTBconsejoCRUD;
    public javax.swing.JTextArea txtConsejoDia;
    public javax.swing.JTextArea txtConsejoEntrenar;
    // End of variables declaration//GEN-END:variables
}
